-- Run this in Supabase SQL Editor.
-- It creates tables for swipe tracking and Instagram submissions with RLS.

create table if not exists public.swipe_events (
  id bigint generated by default as identity primary key,
  session_id text not null,
  profile_id text not null,
  action text not null check (action in ('like', 'nope', 'super_like')),
  referral_code text,
  client_created_at timestamptz,
  source_url text,
  user_agent text,
  meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists swipe_events_created_at_idx
  on public.swipe_events (created_at desc);
create index if not exists swipe_events_action_idx
  on public.swipe_events (action);

create table if not exists public.instagram_submissions (
  id bigint generated by default as identity primary key,
  session_id text not null,
  instagram_handle text not null
    check (instagram_handle ~ '^[A-Za-z0-9._]{1,30}$'),
  referral_code text,
  message text,
  consent boolean not null default false,
  source_url text,
  user_agent text,
  created_at timestamptz not null default now()
);

-- For existing projects that created the earlier schema version.
alter table public.swipe_events
  add column if not exists referral_code text;

alter table public.instagram_submissions
  add column if not exists referral_code text;

alter table public.instagram_submissions
  add column if not exists message text;

alter table public.instagram_submissions
  drop constraint if exists instagram_submissions_message_len_chk;
alter table public.instagram_submissions
  add constraint instagram_submissions_message_len_chk
  check (message is null or char_length(message) <= 500);

create index if not exists instagram_submissions_created_at_idx
  on public.instagram_submissions (created_at desc);
create index if not exists instagram_submissions_handle_idx
  on public.instagram_submissions (instagram_handle);

alter table public.swipe_events enable row level security;
alter table public.instagram_submissions enable row level security;

drop policy if exists "anon insert swipe events" on public.swipe_events;
create policy "anon insert swipe events"
  on public.swipe_events
  for insert
  to anon
  with check (true);

drop policy if exists "anon insert ig submissions" on public.instagram_submissions;
create policy "anon insert ig submissions"
  on public.instagram_submissions
  for insert
  to anon
  with check (consent = true);

grant usage on schema public to anon;
grant usage, select on all sequences in schema public to anon;
grant insert on table public.swipe_events to anon;
grant insert on table public.instagram_submissions to anon;
